awslabs/LISA

Makefile, scripts/convert-and-upload-model.sh, scripts/convert-to-safetensors.py, scripts/fast-s3-transfer.sh
N/A
MistralAI models on hugging face require acceptance of a user agreement prior to access. This PR updates the model prep script to prompt the user for their access token and to login to huggingface prior to downloading the model artifacts.
=> Update model prep scripts to support huggingface login

lib/user-interface/react/src/components/model-management/ModelManagementUtils.tsx, lib/user-interface/react/src/components/model-management/create-model/BaseModelConfig.tsx, lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx, lib/user-interface/react/src/shared/model/model-management.model.ts
Updated Model cards to display Hosted Platform and Instance type. Also update create API call to pass in ModelURL so that the call will complete.
=> Updating UI cards and added ModelURL to API call for create

Makefile
=> adding npm install in Makefile

lib/user-interface/index.ts
=> Env file typo during generation

lambda/models/state_machine/create_model.py
Add model data to ddb at beginning of state machine
=> Add model data to ddb at beginning of state machine

lib/serve/rest-api/src/requirements.txt
=> Remove crypto Dependency from LISA Serve

lambda/utilities/fastapi_middleware/aws_api_gateway_middleware.py
Fixed an issue where FastAPI was setting the wrong path for the openapi.json definition depending on if it was being served with the stage prefix (from APIGW) or with without (from APIGW with a custom domain).
=> Fixed issue where /docs would fail to serve from APIGW with a custom domain

lib/user-interface/react/src/components/model-management/ModelManagementActions.tsx, lib/user-interface/react/src/components/model-management/ModelManagementUtils.tsx, lib/user-interface/react/src/components/model-management/create-model/AutoScalingConfig.tsx, lib/user-interface/react/src/components/model-management/create-model/BaseModelConfig.tsx, lib/user-interface/react/src/components/model-management/create-model/ContainerConfig.tsx, lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx, lib/user-interface/react/src/components/model-management/create-model/LoadBalancerConfig.tsx, lib/user-interface/react/src/shared/form/environment-variables.tsx, lib/user-interface/react/src/shared/model/model-management.model.ts, lib/user-interface/react/src/shared/reducers/model-management.reducer.ts
Updating the UI to accept camel case for model management APIs, also fixing default values so that it will properly create externally hosted models.
Fixed a small bug around environment not properly being sent to BE.
=> UI API Updates

lib/user-interface/react/src/components/model-management/ModelManagementActions.tsx
Disabling the actions that won't be initially released
=> Disabling actions that won't be available with LISA 3.0.0

README.md
Readme changes to showcase rolling back ALB behind APIGW
=> Readme changes to showcase rolling back ALB behind APIGW

lib/user-interface/react/src/components/model-management/create-model/AutoScalingConfig.tsx, lib/user-interface/react/src/components/model-management/create-model/ContainerConfig.tsx, lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx, lib/user-interface/react/src/components/model-management/create-model/LoadBalancerConfig.tsx, lib/user-interface/react/src/shared/model/model-management.model.ts
Field validation to force required fields
=> Updating to account for field validation

lambda/models/domain_objects.py, lambda/models/lambda_functions.py
Updates the API model and API stub so that the UI may be worked on in parallel while the API is under development.
Tested by validating errors with the following commands, token and apigw url in my env:
```shell
curl -X PUT -H "Authorization: $token" -H 'Content-Type: application/json' ${endpoint}/models/my-cool-model-name -d '{"modelType": "textgen"}'
curl -X PUT -H "Authorization: $token" -H 'Content-Type: application/json' ${endpoint}/models/my-cool-model-name -d '{"streaming": false}'
curl -X PUT -H "Authorization: $token" -H 'Content-Type: application/json' ${endpoint}/models/my-cool-model-name -d '{"autoScalingInstanceConfig": null}'  # expected error
curl -X PUT -H "Authorization: $token" -H 'Content-Type: application/json' ${endpoint}/models/my-cool-model-name -d …
```
=> Update API model and API stub for UpdateModel

lib/user-interface/react/src/components/model-management/create-model/AutoScalingConfig.tsx, lib/user-interface/react/src/components/model-management/create-model/ContainerConfig.tsx, lib/user-interface/react/src/components/model-management/create-model/LoadBalancerConfig.tsx
Added units for create Model form fields so it is a little less confusing.
=> Added units for create Model form fields

ecs_model_deployer/src/lib/ecsCluster.ts
Added output for ASG name in model stacks.
=> Added Output for ASG name to the model CDK infra

.github/workflows/code.release.branch.yml
=> fix sed command

lib/user-interface/react/src/shared/model/model-management.model.ts
I think we can do a better job about selecting default values in the create model form, here are some updates to limit the amount of updates required.
=> updating UI default values

.github/workflows/code.hotfix.branch.yml, .github/workflows/code.release.branch.yml, lib/user-interface/react/index.html, lib/user-interface/react/package-lock.json, lib/user-interface/react/package.json, lib/user-interface/react/scripts/set-revision-info.mjs, lib/user-interface/react/src/components/Topbar.tsx, lib/user-interface/react/src/main.tsx
Displaying LISA version in UI so it is clear to our customers what version of the system they are using when trying to debug/troubleshoot issues.
=> Adding LISA version to dropdown in UI

lib/user-interface/react/src/components/chatbot/FileUploadModals.tsx
When converting the chat UI to pull the models from the new model management list endpoint, there was a conversion missed when passing the embedding model in for file ingestion. Fixed with a simple model translation.
=> Fixed RAG file upload

lambda/models/state_machine/update_model.py
Update workflow was failing on updating metadata values for models that are not hosted in LISA (e.g. Bedrock Foundation Models). This set of changes removes the assumptions that all models will have an autoscaling group and a warmup value defined. Validated that my state machines no longer fail and that the metadata is updated appropriately.
=> Fix: allow updates for LiteLLM-only models

.github/workflows/docs.deploy.github-pages.yml, README.md, lib/docs/.vitepress/config.mts
Updating Github docs publisher to reflect correct repository name
=> Update LISA repo name

Makefile, README.md, package.json
Adding support for finch to allow deployments from OSX or other systems that use an alternative to docker. 
=> Add finch support

ecs_model_deployer/src/lib/lisa_model_stack.ts
=> Enabled IMDSv2 for model stack launch template

lib/api-base/utils.ts, lib/networking/vpc/index.ts, lib/rag/index.ts, lib/schema.ts, lib/serve/index.ts, package-lock.json, package.json
Update our code so that if subnets are provided we don't make external EC2 calls to get CIDR block.
=> Update Subnet and CIDR structure

lib/models/ecs-model-deployer.ts
create role and policies at the same time
=> Create role and policies all at once

Makefile, lib/schema.ts, lib/stages.ts
Adding config to convert inline policies to managed policies
=> Convert inline policies to managed policies

.pre-commit-config.yaml, lambda/models/handler/create_model_handler.py, lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx, lib/user-interface/react/src/shared/model/model-management.model.ts, lib/user-interface/react/src/shared/validation/index.ts
Adding some validation to the create model API handler
=> Update create model validation; Ensure Base image is set for LISA hosted models

lib/user-interface/react/src/components/chatbot/Chat.tsx, lib/user-interface/react/src/components/chatbot/Message.tsx, package-lock.json, package.json
Added Icons to indicate who is chatting and updated input text area size.
=> Chat UI cleanup

lib/docs/admin/ui-configuration.md, lib/docs/user/chat.md, lib/user-interface/react/src/App.tsx, lib/user-interface/react/src/components/chatbot/Chat.tsx, lib/user-interface/react/src/components/chatbot/Sessions.tsx
Documentation for Doc Summarization feature
=> Documentation for Doc Summarization feature

lib/user-interface/react/src/components/Topbar.tsx, lib/user-interface/react/src/components/configuration/createRepository/RdsConfigForm.tsx, lib/user-interface/react/src/shared/modal/ReviewChanges.tsx, lib/user-interface/react/src/shared/util/zodUtil.ts, lib/user-interface/react/tsconfig.json
Correct zod defaults used in UI modal 
=> Fix zod schema defaults in UI modal

example_config.yaml, lib/api-base/authorizer.ts, lib/api-base/utils.ts, lib/configSchema.ts, lib/models/docker-image-builder.ts, lib/models/state-machine/create-model.ts, lib/models/state-machine/delete-model.ts, lib/models/state-machine/update-model.ts, lib/rag/state_machine/delete-pipeline.ts, lib/rag/state_machine/ingest-pipeline.ts
=> Support deploying LISA more than once in a single account

.github/workflows/test-and-lint.yml, Makefile, lambda/prompt_templates/__init__.py, lambda/utilities/common_functions.py, lib/user-interface/react/src/components/chatbot/Chat.tsx, requirements-dev.txt, test/lambda/test_prompt_templates_lambda.py, test/lambda/test_repository_lambda.py, test/lambda/test_session_lambda.py
=> Unit tests for Repos and Prompt Templates

lib/api-base/authorizer.ts, lib/api-base/utils.ts, lib/models/docker-image-builder.ts, lib/models/state-machine/create-model.ts, lib/models/state-machine/delete-model.ts, lib/models/state-machine/update-model.ts, lib/serve/index.ts, lib/stages.ts, test/cdk/mocks/MockApp.ts, test/cdk/stacks/nag.test.ts
We don't use the DLQs that are configured with our lambdas, we shouldn't be standing up this infrastructure and not use it. Removed these and suppressed the CDK nag findings for it.
=> Remove Lambda DLQs

Makefile, requirements-dev.txt, test/lambda/test_authorizer_lambda.py, test/lambda/test_configuration_lambda.py
Adding tests for our authorizer and configuration lambdas. This bumps coverage up to 33%
=> Authorizer and Configuration unit tests

lib/schema/configSchema.ts, lib/user-interface/react/src/components/chatbot/Chat.tsx
=> P5 support

bin/copy-deps.sh, bin/package-lambda-layer, ecs_model_deployer/package.json, lambda/dockerimagebuilder/__init__.py, lib/docs/package.json, lib/serve/ecs-model/embedding/tei/Dockerfile, lib/serve/ecs-model/textgen/tgi/Dockerfile, lib/serve/ecs-model/vllm/Dockerfile, lib/serve/rest-api/Dockerfile, lib/user-interface/react/package.json, package.json, scripts/copy-deps.sh, vector_store_deployer/package.json
This is a PR to incorporate changes from our mirror that aren't Amazon tooling specific.
=> Incorporate Pipeline Changes

lib/user-interface/react/src/components/chatbot/Chat.tsx
Updated a Chat component hook to bind to the `isAuthenticated` attribute instead of the whole `auth` object.
=> Update UI components to support dynamic auth method selection

lib/serve/rest-api/src/utils/generate_litellm_config.py, lib/serve/serveApplicationConstruct.ts
=> added conditional auth

cypress/src/smoke/fixtures/configuration.json, lib/chat/api/configuration.ts, lib/user-interface/react/src/App.tsx, lib/user-interface/react/src/components/Topbar.tsx, lib/user-interface/react/src/components/chatbot/Chat.tsx, lib/user-interface/react/src/components/configuration/ActivatedUserComponents.tsx, lib/user-interface/react/src/shared/model/configuration.model.ts
- Enabling Admins to enable/disable MCP Server connections
- Fixed routing to properly add or remove routes based on configuration
=> Allow admins to enable/disable MCP Server Connections

lambda/management_key.py, lib/serve/serveApplicationConstruct.ts, lib/stages.ts, test/cdk/mocks/MockApp.ts, test/cdk/stacks/nag.test.ts, test/cdk/stacks/roleOverrides.test.ts, test/lambda/test_management_key.py
Adding secret rotation for LISA Serve
=> Secret rotation enablement for LISA Serve

lib/user-interface/react/src/components/chatbot/Chat.tsx, lib/user-interface/react/src/components/chatbot/hooks/chat.hooks.tsx, lib/user-interface/react/src/components/chatbot/hooks/useToolChain.hooks.tsx, lib/user-interface/react/src/components/configuration/ActivatedUserComponents.tsx, lib/user-interface/react/src/shared/modal/confirmation-modal.tsx, lib/user-interface/react/src/shared/reducers/modal.reducer.ts, test/lambda/test_management_key.py
Added the following to support guardrails:
- Added stop button so user can break the AI/Tool Call loop
- Added infinite loop prevention, requiring user feedback after 20 continuous AI/Tool calls
- Defaulting into "Safe Mode" requiring user approval prior to calling tools (overrides coming next PR)
=> MCP Guardrails

lambda/mcp_server/lambda_functions.py
- Non admin users can see all MCP connections list even if they aren't global
- Toggling a server not owned by the admin to global, causes a duplicate entry
=> Fix: Admin MCP Updates and Filtering Fixes

lambda/authorizer/lambda_functions.py, lib/api-base/authorizer.ts, lib/api-base/fastApiContainer.ts, lib/docs/admin/getting-started.md, lib/docs/admin/idp-config.md, lib/docs/config/configuration.md, lib/schema/configSchema.ts, lib/serve/rest-api/src/api/endpoints/v2/litellm_passthrough.py, lib/serve/rest-api/src/auth.py, lib/user-interface/react/src/components/app-configured.tsx, lib/user-interface/react/src/main.tsx, lib/user-interface/userInterfaceConstruct.ts
Some customers don't want everyone in their IDP to have access to LISA, providing the option to provide a userGroup that will allow users access to the application
=> Optional LISA User Group Config

Makefile, lambda/repository/pipeline_delete_documents.py, lambda/repository/pipeline_ingest_documents.py, lambda/repository/rag_document_repo.py, requirements-dev.txt, test/lambda/test_constants.py, test/lambda/test_dockerimagebuilder.py, test/lambda/test_file_processing.py, test/lambda/test_pipeline_delete_documents.py, test/lambda/test_pipeline_ingest_documents.py, test/lambda/test_pipeline_ingestion.py, test/lambda/test_rag_document_repo_lambda.py, test/lambda/test_repository_state_machine_lambda.py
=> Expanding Unit Test Coverage

lib/docs/config/model-management-ui.md, lib/docs/user/model-library.md
Docs for v5.1 model management.
=> docs for model mgmt

lib/schema/ragSchema.ts, lib/user-interface/react/src/components/chatbot/components/RagOptions.tsx, lib/user-interface/react/src/components/configuration/RepositoryTableConfig.tsx, lib/user-interface/react/src/components/configuration/createRepository/RepositoryConfigForm.tsx
Adding ability to define an optional default embedding model when creating/updating vector store.
When selecting a vector store, if a default is defined that is automatically selected in the chat.
=> Vector Store default embedding model

.github/workflows/code.end-to-end-test.nightly.yml, lib/rag/vector-store/state_machine/delete-store.ts, lib/rag/vector-store/vector-store-creator.ts, test/cdk/stacks/nag.test.ts
Fixing app sec findings for overly permissive IAM permissions on our vector store creator role
=> Trim vector store permissions

lambda/session/lambda_functions.py, lib/user-interface/react/src/components/chatbot/components/Sessions.tsx, lib/user-interface/react/src/components/types.tsx
Group sessions relative to when they happened in history.
=> Time based session grouping

lib/user-interface/react/src/components/chatbot/hooks/mcp.hooks.tsx, lib/user-interface/react/src/components/mcp/McpServerDetails.tsx, lib/user-interface/react/src/components/mcp/McpServerForm.tsx, lib/user-interface/userInterfaceConstruct.ts
Fixing Oauth Callback for our hosted UI
This had worked locally but was failing in S3 deployments.
=> Fix/Oauth Callback for hosted UI
