awslabs/LISA

- README.md
- lib/schema.ts
- lib/serve/ecs-model/vllm/Dockerfile
- lib/serve/ecs-model/vllm/src/entrypoint.sh
- lib/serve/index.ts
- lib/serve/rest-api/src/main.py
This commit adds support for vLLM containers with some example documentation to support it. The schema has been updated to allow for the vLLM container. These changes help toward the migration to the v2.x architecture.
1. Update README with examples of usage
2. Update schema to guarantee no periods in names so that I can split on them later
3. Add Dockerfile and entrypoint script for vLLM-served models
4. Add a short-circuit for non-TGI/TEI containers so that we don't fail on "registering" the model, which will be deprecated as part of an upcoming v2 release.
> Add support for vLLM containers

- README.md
- example_config.yaml
- lib/schema.ts
- lib/user-interface/index.ts
- lib/user-interface/react/src/components/chatbot/Chat.tsx
- lib/user-interface/react/src/components/chatbot/RagOptions.tsx
- lib/user-interface/react/src/components/types.tsx
- lib/user-interface/react/src/components/utils.ts
- lib/user-interface/react/src/main.tsx
- test/cdk/mocks/config.yaml
- Updated UI to pull Models from config vs API, this allows us to get supplemental info
- UI now only separates textgen vs embedding models in dropdowns, also only enables streaming for models that support it
- Fixed longstanding bug where switching to a model with streaming active to a model that doesn't support streaming "locks" streaming as enabled
> Split textgen and embedding models in UI

- README.md
This set of changes updates the README file with more documentation and clarifications from the previous update. This also utilizes the architecture diagram for LISA Serve that I uploaded but failed to reference.
This adds information about getting values for the authConfig and clarifications for the OpenAI spec support and configuration for LiteLLM.
> Add documentation updates for IdP, clarifications on LiteLLM setup

- lib/serve/rest-api/src/api/routes.py
As we encourage users to use the v2 routes, we don't want to entirely remove v1 just yet, but we do want to discourage its usage. From the OpenAPI docs that are generated, I can now see that the /v1/ routes are deprecated, and only the v2 routes and health check route are still supported. Screenshot of the docs page from FastAPI attached: 
I validated that the v1 routes still work alongside the v2 routes. This is mostly a cosmetic change.
> Deprecate v1 routes in favor of v2

- lib/schema.ts
- lib/serve/rest-api/src/utils/generate_litellm_config.py
I received a report that one of my recent changes was causing an error when deploying the REST API container without a LiteLLM models list defined, which is the default for new config files. Because it was left as a null value and not an array, the Python file for generating the rest of the LiteLLM config received a None instead of an empty list. This fix includes two fixes for the same issue:
1. On the typescript side, the schema was updated so that it forces an array if the array is not defined. The "default" function only applies if the field is `undefined`, not if it's `null`: the case we're solving for.
2. On the python side, we now check if the model list is truthy before trying to extend it, which catches the None case. If it is None (or any falsy value), it'll return an empty …
> Fix None values from config file where array is expected

- lisa-sdk/LISA_v2_demo.ipynb
Add a Jupyter notebook to show how to use LISA using the OpenAI API. This is primarily an overview of OpenAI features, but using the LISA endpoint in the client instead of any other LLM hosting solutions. I was able to run this entire demo against my own testing account, which has an API token configured and DNS + certificate for SSL validation against my LISA Serve ALB. For ease of reviewing, here's a link to the rendered notebook so you don't have to strictly review JSON: https://github.com/awslabs/LISA/blob/26fb3c65a1c7aa86964d7676a39aeec0c36ed7db/lisa-sdk/LISA_v2_demo.ipynb
> Add demo Jupyter notebook for v2

- README.md
This set of changes removes the v1 reference in the token creation docs, and also adds a blurb right at the top of the readme about migrating to the v2 endpoints.
> Add v1 deprecation notes to README

- README.md
- lisa-sdk/lisapy/langchain.py
This change adds explicit support for vLLM embedding models (all one of them so far) for use within LISA. Either LiteLLM or LangChain was defaulting the embeddings API to using base64 as the encoding format, which the intfloat model threw errors on. By changing the encoding format to float, we preserve the functionality of the existing RAG implementation, and prevent the intfloat model from failing when it's called with default parameters.
Tested by deploying to my account and using the intfloat model for document upload and search within the chat UI.
> Add support for vLLM embedding models

- lib/user-interface/react/src/components/chatbot/ModelKwargs.tsx
For models that are using vLLM, they respond nicely if the top_p parameter is not set, but the TGI models fail with an unclear message in the chat UI unless you're looking directly at the network calls in your browser. vLLM allows values for top_p within 0<N<=1, but TGI requires 0<N<1, which is where that error comes from if the value is not set and we default to `1` for the parameter.
Because there's a good chance our users are going to use a TGI container for their models, setting the value to 0.01 does not greatly impact the quality of responses that come back from either model (tested with mistral-7b on both TGI and vLLM).
The goal of this change is to reduce the amount of friction it takes to get started with the Chat UI out of the box, regardless of which model is being used.
For …
> Add default top_p value for Chat UI

- example_config.yaml
For documentation purposes, this change makes the example account IDs more consistent with the rest of the repo's use of the `012345678901` number.
> Add example account IDs to example config

- lib/user-interface/react/src/components/chatbot/Chat.tsx
- lib/user-interface/react/src/components/chatbot/ModelKwargs.tsx
- lib/user-interface/react/src/components/types.tsx
The LangChain JS library sets some default values for presence and frequency penalties if we don't set them as part of the OpenAI client. As a result, we end up with a non-required numeric value (0) that we did not intend to put there, which heavily degrades the model responses on tgi containers. These changes override the defaults set by the client so that the values are either the numeric value we set, including 0, otherwise they will be null. I validated that this happens by setting and unsetting the values in the model kwargs of the Chat UI and checked the request data from the network tab of my browser. Now, by default, these values won't be set unless we want them to be.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> Set default penalty params to null when unspecified

- example_config.yaml
- lambda/utilities/vector_store.py
- lib/api-base/fastApiContainer.ts
- lib/rag/index.ts
- lib/schema.ts
- lib/serve/index.ts
- lib/serve/rest-api/src/api/endpoints/v2/litellm_passthrough.py
- lib/serve/rest-api/src/requirements.txt
- lib/serve/rest-api/src/utils/generate_litellm_config.py
- test/cdk/mocks/config.yaml
- test/cdk/stacks/serve.test.ts
This set of changes adds a PostgreSQL database to the Serve infrastructure to help with scaling LiteLLM across multiple instances. This database will be used between multiple REST API containers so that models that are dynamically added to a running LiteLLM instance will update the DB and be available across all other REST API containers behind the LISA Serve endpoint.
Tests have increased error counts because the database is a Single-AZ db. This is expected to be fine because the database is only used for this one purpose and is not anticipated to have any form of high load on it.
This database will be used in further model management feature development.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Add PostgreSQL db for LiteLLM scaling

- lambda/models/lambda_functions.py
- lib/user-interface/react/src/App.tsx
- lib/user-interface/react/src/components/model-management/ModelManagementActions.tsx
- lib/user-interface/react/src/components/model-management/ModelManagementComponent.tsx
- lib/user-interface/react/src/components/model-management/ModelManagementUtils.tsx
- lib/user-interface/react/src/shared/modal/confirmation-modal.tsx
- lib/user-interface/react/src/shared/reducers/index.ts
- lib/user-interface/react/src/shared/reducers/modal.reducer.ts
When doing destructive actions we want to make sure our users are prompted for confirmation prior to that action being taken. That being said, I have added a confirmation modal that will ask the user if they are sure they want to proceed prior to taking any model start/stop/delete action. This can be seen in the below demo:
> Adding confirmation modal for start/stop/delete actions

- lambda/utilities/file_processing.py
- lib/rag/layer/requirements.txt
This commit gets rid of one of the dependabot security issues.
https://github.com/awslabs/LISA/security/dependabot/1
* Gets rid of a dependabot security issue. Tested that this works by deploying to test account and uploading a pdf in the RAG UI. Validated that the PDF was successfully parsed and embedded and that I could retrieve context from its contents.
* I also alphabetized the dependencies
> Upgrade pypdf version

- lib/api-base/fastApiContainer.ts
- lib/serve/rest-api/src/api/endpoints/v2/litellm_passthrough.py
- lib/serve/rest-api/src/auth.py
- lib/serve/rest-api/src/requirements.txt
This set of changes prevents non-admins from performing mutating operations on LiteLLM itself, including, but not limited to adding or deleting models, creating API keys, and more. If the route is a known OpenAI API route, then any authenticated user may use it, but if not, then an administrator, as identified by an IdP-provided admin group, must make the API call. If the user attempts to make these calls but is not an admin, then the request is rejected.
> Lock down LiteLLM administrative APIs to admin users

- lib/schema.ts
We had some stories of deployment pains when users had accounts with leading 0's in their account IDs. We already had validation but because it wasn't clear that the error was due to yaml cutting off the leading 0's from a number, customers were not always sure how to resolve the error.
> Add more helpful messaging to account validation error

- lambda/models/clients/__init__.py
- lambda/models/clients/litellm_client.py
- lambda/models/exception/__init__.py
- lambda/models/handler/__init__.py
- lambda/models/handler/base_handler.py
- lambda/models/handler/delete_model_handler.py
- lambda/models/handler/get_model_handler.py
- lambda/models/handler/list_models_handler.py
- lambda/models/handler/utils.py
- lambda/models/lambda_functions.py
- lib/core/layers/fastapi/requirements.txt
- lib/models/index.ts
- lib/models/model-api.ts
- lib/stages.ts
This set of changes implements the ListModels, GetModel, and DeleteModel API for the model management feature. 
* ListModels will list all the models that are stored in the LiteLLM database and return any information that we store as additional metadata through the Create API once that one is implemented.
* GetModel will get the metadata for one specific model. It appears LiteLLM is unable to filter for the model on its own, so this is implemented as a filter over the ListModels API.
* DeleteModel in its current form will delete a reference from LiteLLM. Once we have more information from the CreateModel API, we can add logic to delete the CloudFormation stack associated with the custom infrastructure we spin up for users in this API.
Main changes
* Addition of LiteLLM client to make the …
> Implement ListModels, GetModel, DeleteModel model management APIs

- lambda/models/clients/litellm_client.py
- lambda/models/handler/base_handler.py
- lambda/models/lambda_functions.py
- lambda/utilities/common_functions.py
- lib/models/model-api.ts
Adds a fix for when self-signed certs are in use instead of a public certificate from ACM
> Add self-signed cert support for model management operations

- lambda/dockerimagebuilder/__init__.py
- lambda/models/exception/__init__.py
- lambda/models/handler/__init__.py
- lambda/models/handler/create_model_handler.py
- lambda/models/handler/delete_model_handler.py
- lambda/models/lambda_functions.py
- lambda/models/state_machine/__init__.py
- lambda/models/state_machine/create_model.py
- lambda/models/state_machine/delete_model.py
- lib/models/model-api.ts
- lib/models/state-machine/constants.ts
- lib/models/state-machine/create-model.ts
- lib/models/state-machine/delete-model.ts
This set of changes adds state machines for handling the creation and deletion of models. These can be used as examples for the eventual implementation of the UpdateModel workflow. This includes, but does not fully implement files for CreateModel, but those will be filled out in a future revision.
* add models table
* add state machine infrastructure for DeleteModel
* add lambda functions for DeleteModel
* add state machine infrastructure for CreateModel
* add lambda functions for CreateModel
* state machine lambdas are created within VPC
* The CreateModel workflow is just a skeleton and it is not fully built out. This is intentional to allow others to implement its components in parallel in future revisions.
* LiteLLM integration has not been added to the state machines. These are …
> Add Create and Delete state machines for model management

- lambda/dockerimagebuilder/__init__.py
- lambda/models/state_machine/create_model.py
- lib/models/docker-image-builder.ts
- lib/models/ecs-model-deployer.ts
- lib/models/model-api.ts
- lib/models/state-machine/create-model.ts
Implement docker image build piece of state machine
> DockerImageBuild state machine implementation

- lib/serve/index.ts
- test/cdk/stacks/serve.test.ts
Adds bedrock and sagemaker permissions so that they don't need to be added to the rest API role manually anymore.
Tested by invoking a bedrock model and an sm endpoint in my account.
> Add Bedrock and SageMaker invoke permissions to REST API container

- lambda/authorizer/lambda_functions.py
- lambda/utilities/common_functions.py
- lib/api-base/authorizer.ts
- lib/api-base/ecsCluster.ts
- lib/api-base/fastApiContainer.ts
- lib/core/api_base.ts
- lib/networking/vpc/index.ts
- lib/serve/index.ts
- lib/stages.ts
- test/cdk/stacks/core-api-base.test.ts
- test/cdk/stacks/networking.test.ts
- test/cdk/stacks/serve.test.ts
Now that fastapi container is behind our APIGW we can use our authorizer to determine if a user should have access to a specific resource. We now:
- Verify that admins are calling anything that isn't a specific OpenAI URL in `/llm`
- If an invalid Bearer token is provided check to see if it is in our token DB and allow access to only OpenAI URLs if valid and present
> Lambda Authorizer updates

- ecs_model_deployer/src/lib/ecsCluster.ts
- lambda/models/clients/litellm_client.py
- lambda/models/domain_objects.py
- lambda/models/handler/base_handler.py
- lambda/models/handler/create_model_handler.py
- lambda/models/handler/delete_model_handler.py
- lambda/models/handler/get_model_handler.py
- lambda/models/handler/list_models_handler.py
- lambda/models/handler/utils.py
- lambda/models/lambda_functions.py
- lambda/models/state_machine/create_model.py
- lambda/models/state_machine/delete_model.py
- lambda/utilities/common_functions.py
- lib/models/model-api.ts
- lib/models/state-machine/create-model.ts
- lib/models/state-machine/delete-model.ts
- lib/user-interface/react/src/components/model-management/ModelManagementActions.tsx
- lib/user-interface/react/src/components/model-management/ModelManagementComponent.tsx
- lib/user-interface/react/src/components/model-management/ModelManagementUtils.tsx
- lib/user-interface/react/src/components/model-management/create-model/AutoScalingConfig.tsx
- lib/user-interface/react/src/components/model-management/create-model/BaseModelConfig.tsx
- lib/user-interface/react/src/components/model-management/create-model/ContainerConfig.tsx
- lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx
- lib/user-interface/react/src/components/model-management/create-model/LoadBalancerConfig.tsx
- lib/user-interface/react/src/shared/form/environment-variables.tsx
- lib/user-interface/react/src/shared/model/model-management.model.ts
- lib/user-interface/react/src/shared/reducers/model-management.reducer.ts
This set of changes migrates from using the LiteLLM db to store state to the DynamoDB table that we're creating for this purpose. This allows us to store data before the model is fully finished, and lets us add any additional information that we'll need for debugging or investigation later.
Primary set of changes:
* API model refactor for camelcase to avoid Pydantic errors on truly optional parameters
* API handlers updated to accommodate the model refactor
* Relevant info now stored in DDB
* UI updates (from @estohlmann ) to work with API model update
* LiteLLM client no longer handles auth because traffic is all within VPC
> Migrate APIs to DDB instead of LiteLLM db

- lambda/models/domain_objects.py
This sets the streaming parameter to be completely optional when making a CreateModel request. It will default to False if not specified, otherwise it takes on the value from the request. Our UI already mandates the field as a radio button, and since this was required from the start, this won't break any existing models.
Rationale for defaulting to False is that embedding models do not support streaming, and not all text generation models support streaming, so it is a more likely option to be set than True. Future APIs (UpdateModel), will be able to modify this flag later on.
> Make CreateModel streaming param optional

- lib/serve/rest-api/src/api/routes.py
Removes the v1 routes because the will no longer work with the model management API. v1 routes depended on the creation of models from the config.yaml file
We have not done a comprehensive review of all code this affects, so instead of removing seemingly unused code and having it break because there was a reference elsewhere, I am opting to just remove the routes to avoid customers accidentally finding them, and we can clean up the unused code later.
> Remove deprecated v1 routes

- ecs_model_deployer/src/lib/ecsCluster.ts
- lambda/models/state_machine/create_model.py
All ECS-hosted models are expected to be frontend by ALBs with no certificate on them, listening on port 80 because they are within the VPC and the external traffic API handlers have already terminated SSL at the load balancer level. No models are expected to have a cert on them.
Publishing to document the changes that I expect to work, but I have not been able to test them yet because of imports on cross-stack exports and I needed to completely delete my models stack, which is taking a long time because Lambda functions take very long to delete. Once those finish, I can attempt deploying to test the changes again.
> Fix: define model ALB correctly in CFN output

- lib/models/index.ts
- lib/models/model-api.ts
- lib/serve/index.ts
- lib/stages.ts
In 3.0.0 we introduced a secret key to allow for Lambda functions to make LiteLLM management calls while not explicitly being an admin user from the user's IdP. The way how we referenced it across different stacks caused an import/export dependency between stacks, which made the affected resources be immutable, which cannot happen for the sake of future CDK deployments. This set of changes removes the explicit dependency in favor of an SSM StringParameter reference, which lets us take on the dependency without CloudFormation having immutability issues with it.
Tested this by deploying my stack after deleting the `models` and `serve` stacks to get rid of any "import" dependencies. Afterwards, I ran `make deploy` one more time to validate that the secret key would get regenerated and not …
> Fix: remove import/export dependency between stacks on management key

- lambda/models/exception/__init__.py
- lambda/models/state_machine/create_model.py
- lambda/models/state_machine/delete_model.py
- lib/models/state-machine/create-model.ts
Adds error catching to the Create workflow so that we properly set a model to Failed if we are unable to copy the Docker image or if we have issues with CloudFormation taking too long or failing parameter validation through CDK. The custom exception messages allow us to send the input dictionary (with all request metadata) to the exception handler, otherwise we'd *only* know the exception message but nothing unique about the model.
This also adds a fix on the Delete side where we were previously unable to delete a model if it didn't create correctly with a LiteLLM ID (common if the model fails creation before that point).
Tested with the following payloads to ensure that the models would fail in a controlled way and that we'd properly handle the failures (and then deleted all of them …
> Fix: add error catching to Create API, allow model Deletes when LiteLLM ID is not present

- lambda/models/domain_objects.py
Adds an "enabled" field to the UpdateModel API so that we can easily start or stop a model from the UI or from the CLI.
> Add enabled field to UpdateModel for start and stop operations

- lambda/authorizer/lambda_functions.py
- lambda/utilities/common_functions.py
- lib/api-base/authorizer.ts
- lib/serve/index.ts
- lib/serve/rest-api/src/api/endpoints/v2/litellm_passthrough.py
- lib/serve/rest-api/src/auth.py
- test/cdk/stacks/core-api-base.test.ts
Starting with the 3.0 release, which introduced dynamic model management, we required admin authentication through an IdP to manage models. However, this approach doesn't work in certain scenarios. To address this, the PR introduces a new authentication method using the model management token secret.
*Testing:*
- I am able to create a model using the Model Management UI 
- I am able to create a model by submitting a POST request to the APIGW endpoint `/model` using the model management token
- I am not able create a model by submitting a POST request to the APIGW endpoint `/model` without the management token
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Adds new authentication method for model management API

- README.md
Discovered from issue: https://github.com/awslabs/LISA/issues/101 the blurb I had written about the `path` was removed when we rewrote the README file. this change adds it back
> Add functionality change between v2 and v3

- lambda/authorizer/lambda_functions.py
- lib/user-interface/react/src/components/chatbot/Chat.tsx
- lib/user-interface/react/src/components/chatbot/RagOptions.tsx
- lib/user-interface/react/src/shared/reducers/model-management.reducer.ts
Prior to 3.0 the models dropdown was populated via `env.js`. Now that model management is dynamic this needs to be populated via the `/models` endpoint in APIGW. This PR loosens the authorization restrictions on this resource to only require a valid jwt token (as opposed to being an admin) and uses this to populate the dropdown.
> Populate model dropdown from /models endpoint

- lib/user-interface/react/src/components/model-management/ModelManagementActions.tsx
- lib/user-interface/react/src/shared/model/model-management.model.ts
- lib/user-interface/react/src/shared/reducers/model-management.reducer.ts
Updating to enable the start and stop APIs. This also removes the stand alone apis for calling the update API and passing the enabled flag. Added logic to enable these options only for LISA hosted models in the correct status.
> Update Start/Stop api calls from UI

- Makefile
- README.md
- example_config.yaml
- lib/core/utils.ts
- lib/iam_stack.ts
- lib/schema.ts
- lib/user-interface/index.ts
- test/cdk/mocks/config.yaml
When creating LISA 3.0 we removed the ability for users to define models and have them deployed at deploy time from the config file. Updating the schema to optionally provide the required fields to pull and validate model weights are present in the S3 bucket. Also redefined the schema structure to support the optional array and removed values. The new field will look like so:
```
ecsModels:
- modelName: meta-llama/Meta-Llama-3-8B
baseImage: vllm/vllm-openai:v0.4.3
inferenceContainer: vllm
- modelName: mistralai/Mistral-7B-Instruct-v0.2
baseImage: ghcr.io/huggingface/text-generation-inference:2.0.1
inferenceContainer: tgi
- modelName: e5-large-v2
baseImage: ghcr.io/huggingface/text-generation-inference:2.0.1
inferenceContainer: tei
- modelName: google/flan-t5-xl …
```
> ECS Config Refactor in config.yaml

- lib/user-interface/react/src/components/model-management/ModelManagementActions.tsx
- lib/user-interface/react/src/components/model-management/create-model/AutoScalingConfig.tsx
- lib/user-interface/react/src/components/model-management/create-model/BaseModelConfig.tsx
- lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx
- lib/user-interface/react/src/shared/model/model-management.model.ts
LISA 3.0 launched with model management but didn't have updating models enabled yet. This PR add the ability to configure a few model properties after launch.
- enable/disable streaming
- model type (textgen/embedding)
- auto scaling configuration (LISA hosted models only)
> Model Management: Enable update form

- lib/user-interface/react/src/components/model-management/create-model/BaseModelConfig.tsx
- lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx
- lib/user-interface/react/src/shared/model/model-management.model.ts
Added some enhancements to the Create Model form to help prevent invalid settings.
- added `(optional)` label to Model URL
- `Model Id` validator now has character limits
- `Instance Type` & `Inference Container` now are required if `LISA Hosted Model` is true 
> Added additional validation to Create Model form

- lambda/models/domain_objects.py
- lambda/models/exception/__init__.py
- lambda/models/handler/base_handler.py
- lambda/models/handler/update_model_handler.py
- lambda/models/lambda_functions.py
- lambda/models/state_machine/create_model.py
- lambda/models/state_machine/update_model.py
- lib/models/model-api.ts
- lib/models/state-machine/update-model.ts
Creates UpdateModel state machine implementation with frontend handler validations to force as many synchronous validations as possible before actually hitting the async workflow, which is a much user friendly experience, and easier to debug.
Model only polls for capacity between stopped and in-service states as the model is still functional in other scenarios. When starting a model, the state machine first waits for the desired number of instances to spin up, THEN it waits for the user-defined warmup time before adding the model to LiteLLM, that way customers can't try to make inference requires prior to the models actually spinning up. the model instances pop up healthy before the models are fully initialized, so this wait is necessary to ensure that the models are working before we …
> Implement UpdateModel backend workflow

- lib/user-interface/react/src/components/chatbot/Chat.tsx
- lib/user-interface/react/src/components/chatbot/RagOptions.tsx
- lib/user-interface/react/src/components/model-management/ModelManagementActions.tsx
- lib/user-interface/react/src/components/model-management/ModelManagementUtils.tsx
- lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx
- lib/user-interface/react/src/shared/model/model-management.model.ts
- Stopped models still show in the UI, which will cause 5xx issues because the model isn't in LiteLLM
- Cannot set a model to streaming or textgen from the UI. The payload doesn't include them
- Payload for UpdateModel needs to be called autoScalingInstanceConfig instead of autoScalingConfig
- Models that were just stopped in the UI cannot be started unless I refresh my page, even after the model shows as Stopped
> Update Model UI fixes

- lambda/models/domain_objects.py
Fixes a bug where the UI could not progress if the inference container was not provided in the GetModel response payload. The data already exists in DDB, and the method to convert the blob back into a LISA model was already looking at (but ignoring) the field, so just adding to the model is sufficient for the field to show in response payloads now.
Example from inspecting network browser while listing models: (main line of note is `"inferenceContainer": "vllm",`)
```json
{
"models": [
{
"autoScalingConfig": {
"minCapacity": 1,
"maxCapacity": 1,
"cooldown": 420,
"defaultInstanceWarmup": 180,
"metricConfig": {
"albMetricName": "RequestCountPerTarget",
"targetValue": 30,
"duration": 60,
"estimatedInstanceWarmup": 330
}
},
"containerConfig": {
"baseImage": {
"baseImage": …
```
> Fix: add inferenceContainer to response payload

- lib/serve/index.ts
- lib/stages.ts
With the latest changes to pull the secret management key into the APIGW Authorizer we now need to make sure that the Serve stack is created before API Base stack or else brand new deployments can fail. This change addresses that issue.
> Bug: Fixed CDK stack dependency for secret management key

- lib/serve/index.ts
A previous left in an unnecessary retain policy that would leave old secrets around. This fixes that issue.
> Bug: Removed superfluous retain policy for management secret

- lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx
Adding inference config in the model response caused non-LISA hosted models to not be undateable due to null value. This was causing the form to be in an error state. Parsed out the field if value is null when submitting the value to the form state.
> non lisa model update

- lib/user-interface/react/src/components/chatbot/Chat.tsx
- lib/user-interface/react/src/components/chatbot/FileUploadModals.tsx
- File upload errors weren't displaying in an intuitive way so that the user would know if the file they were uploading was an invalid type.
- Update listener for enter key to not allow user to submit a request if response is running
> Update file upload modal error handling and prevent multiple chat requests at once

- lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx
> Make it so LISA hosted models prop doesn't show up in diff calculations

- lib/user-interface/react/src/components/model-management/ModelManagementActions.tsx
- lib/user-interface/react/src/components/model-management/create-model/CreateModelModal.tsx
make it so failed models can't be updated
don't make update call if diff is empty
> Minor UI updates

- lib/rag/index.ts
- lib/stages.ts
- package-lock.json
- package.json
This set of changes allows customers to use capitalized deployment names by not failing on S3 Bucket naming in the RAG stack. This set of changes updates the API Deployment stack so that it follows the same naming convention as other stacks, enabling multiple deployments to the same region and account. Last, this version bumps to the CDK Labs IAC package so that we benefit from its name uniqueness fixes.
This will create a new "api-deployment" stack, and then the old LisaApiDeployment stack can be safely removed. This now enables deploying multiple "deployments" in the same account and region with isolated resources.
> Fix deployment issues with S3, permissions boundary, API deployment

- lib/user-interface/react/scripts/set-revision-info.mjs
Revision info wasn't working on my cloud desktop, went with an approach that will work on both systems.
> Fixing set revision for linux based system

- ecs_model_deployer/src/lib/ecsCluster.ts
- lib/iam_stack.ts
This change fixes an issue with deploying models after the initial deployment when using the permissions boundary aspect. The new version adds the disambiguation string regardless of whether or not the policy already has a defined name, so we can't just "know" what the policy will be anymore. This change puts the policy ARN into a String Parameter so that we can refer to it in later stacks. We can "know" the string param name, which lets us get the ARN from its value for use in the model stacks.
> Move ECS Policy into SSM param for model deployments

- README.md
- lambda/models/domain_objects.py
- lambda/models/state_machine/create_model.py
- lib/user-interface/react/src/components/model-management/create-model/ContainerConfig.tsx
- lib/user-interface/react/src/shared/model/model-management.model.ts
The "path" component of the ContainerConfig object was redundant and unnecessarily complicated for customers to use. Historically, it referred to the path location of Dockerfiles from the root of the repo to where the model definitions were, but since we add customization on top of containers, we end up requiring that the paths are used. We specify in another option whether the model is using TGI/TEI/vLLM, and for all of these, there's a 1:1 match for it and its corresponding "path" option. The container spinup will fail if these don't match.
As part of the 3.0 release, the path changed even further to be relative to a folder inside of the root, which made it difficult to document and describe how to use it. This change removes it altogether and instead requires the backend to know where …
> Remove "path" from API model

- lambda/models/domain_objects.py
- lambda/models/state_machine/create_model.py
- lambda/utilities/validators.py
Refactors the API model file to add validation on requests, that way we fail much earlier and give users the ability to do client-side troubleshooting before the state machine fails for the same reasons in the backend.
Main validations added:
* Int values specified as positive (>0) or non-negative (>=0)
* strings must have a minimum length of at least 1 to avoid the empty string issues we were seeing
* Removed some of the custom logic for checking against 0 since we have the pydantic types to use instead
* moved autoScalingInstanceConfig validation logic to its corresponding object because the field validation made more sense to happen there.
> Fix: Add synchronous model validation to CreateModel API

- Makefile
Enabling headless deployment in makefile. You can do this by running `make deploy HEADLESS=true`
> Enabling headless deployment in make file

- lib/api-base/authorizer.ts
- lib/api-base/utils.ts
- lib/models/docker-image-builder.ts
- lib/models/state-machine/create-model.ts
- lib/models/state-machine/delete-model.ts
- lib/models/state-machine/update-model.ts
- lib/serve/index.ts
- test/cdk/stacks/chat.test.ts
- test/cdk/stacks/core-api-base.test.ts
Addresses lowest hanging fruit for CDK nag warnings. Reduces nags to 299 from 355.
- added DQL for lambdas w/enforced SSL
- added limits for lambda concurrency
> Updates to address some cdk-nag warnings

- package.json
- scripts/migrate-properties.mjs
Created a utility to migrate the old config.yaml to the new config-custom.yaml
To test run `npm run migrate-properties` and then deploy
> Config migration script

- lib/docs/index.ts
When deploying LISA docs to an account, the stage must match the base url. This changes the url to match the deployed base url in Github. 
> Update Docs gateway stage url to match github

- ecs_model_deployer/Dockerfile
- lambda/dockerimagebuilder/__init__.py
- lib/models/docker-image-builder.ts
Updating LISA to pass in subnet to create instance call if one is provided in the config.
> Adding subnet for ec2 create instance call

- lib/user-interface/react/package-lock.json
- lib/user-interface/react/src/components/chatbot/Chat.tsx
- lib/user-interface/react/src/components/chatbot/FileUploadModals.tsx
Close the file context manager if file ingestion/upload is successful
> Closing file context manager if upload is success

- ecs_model_deployer/src/lib/ecs-schema.ts
When importing external schema defs into the ecs model deployer, it changes the entire structure of the dist folder not allowing the lambda to function, to fix this removing imports and duplicating definitions. 
> Remove imports

- lambda/repository/lambda_functions.py
- lambda/repository/vector_store_repo.py
- lib/configSchema.ts
- lib/rag/index.ts
- lib/user-interface/react/src/components/configuration/RepositoryActions.tsx
- lib/user-interface/react/src/components/configuration/createRepository/OpenSearchConfigForm.tsx
- lib/user-interface/react/src/components/configuration/createRepository/PipelineConfigForm.tsx
- lib/user-interface/react/src/components/configuration/createRepository/RdsConfigForm.tsx
- lib/user-interface/react/src/components/configuration/createRepository/RepositoryConfigForm.tsx
- lib/user-interface/react/src/shared/form/array-input.tsx
- lib/user-interface/react/src/shared/modal/confirmation-modal.tsx
Although legacy vector stores cannot be edited through the UI, we aim to enable their deletion. While this will not remove the resources, it will render them inactive and allow for their destruction during the next deployment. This PR also includes the following UI improvements:
- Disabled the edit option for legacy repositories.
- Updated the create repository form to include descriptions.
- Added a mandatory acknowledgment when deleting legacy repositories, informing users that a deployment is required to actually remove AWS resources.
> Add ability to delete legacy vector stores through UI

- lib/serve/rest-api/src/api/endpoints/v2/litellm_passthrough.py
- lib/user-interface/react/src/components/chatbot/Chat.tsx
LISA has not properly displayed error messages for quite some time, this is because all responses were returning http_status 200. Updated BE to pass back the status code from the proxied call.
> Properly display error messages from proxied calls

- lib/networking/vpc/index.ts
When using an existing VPC and subnets, the subnets were being imported incorrectly, causing an exception during CDK synthesis. This fix addresses the issue by ensuring that subnets are imported with the `ipv4CidrBlock` property defined, as it is required for our configuration.
> Subnet import fix

- lambda/authorizer/lambda_functions.py
- lambda/utilities/common_functions.py
- lib/api-base/authorizer.ts
- lib/core/api_base.ts
- lib/schema/configSchema.ts
- lib/serve/index.ts
- lib/stages.ts
- test/cdk/mocks/MockApp.ts
- Removed hard dependency in schema for RAG and UI to both be deployed
- Added ability for users to be able to auth with LISA APIs with tokens
- Tested this:
- Deployed LISA without UI
- Made API call to create embedding model - with admin secret
- Made API call to create RAG Repo - with admin secret
- Made API call  to ingest document - with token from token table
- Made API call to do similarity search - with token from token table
> Decouple RAG and UI

- lambda/utilities/common_functions.py
- lambda/utilities/file_processing.py
- lambda/utilities/validation.py
- lib/rag/index.ts
Allow users to setup pipeline with 0 chunk size allowing ingestion of entire documents as a single chunk
> Allow pipeline with 0 chunk size

- lambda/repository/lambda_functions.py
- lib/api-base/ecsCluster.ts
- lib/core/layers/common/create_env_variables.py
- lib/serve/rest-api/src/auth.py
- lib/serve/rest-api/src/main.py
To better support customers deploying into isolated regions, this PR will address a number of issues found while testing isolated deployments.
Properly set certificates for lambdas and ECS containers. 
> Properly set certificates for lambdas and ECS containers. 

- ecs_model_deployer/package.json
- lib/docs/package.json
- lib/serve/rest-api/Dockerfile
- lib/user-interface/react/package.json
- lib/user-interface/react/vite.config.ts
- package.json
- vector_store_deployer/package.json
With the last package updates, the vite base parameter wasn't being passed in correctly to build the web application. This updates the package.json build to allow the vite base parameter to be passed into the correct build command. Also, removing the default 'prod' base from vite. 
> Add vite base property

- lib/schema/configSchema.ts
- vector_store_deployer/src/lib/opensearch.ts
When deploying OpenSearch clusters, an issue was encountered where the OpenSearch Domain attempts to access the availabilityZone property on a subnet. However, since the subnets are imported using Subnet.fromSubnetAttributes, the availabilityZone property is not populated, resulting in a runtime exception.
This PR updates the configuration schema to require the availabilityZone property when using private VPCs/subnets, ensuring it is explicitly defined to avoid this issue.
> Added availabilityZone to Subnet config schema

- lib/user-interface/react/vite.config.ts
- lib/user-interface/userInterfaceConstruct.ts
n certain environments, the BASE_URL was not being correctly set during the rendering of Vite templates. This fix ensures that BASE_URL is now properly assigned, restoring the expected behavior across all environments.
> Fix Incorrect BASE_URL Assignment in Vite Templates

- lib/stages.ts
This change fixes the chatStack dependencies. If the `deployMetrics` config option is set to true it is necessary to have the chatStack declare a dependency on the Metrics stack so that the session lambdas deployed by the chatStack are configured correctly.
> fix chat stack dependencies

- lib/user-interface/react/src/components/model-management/components/ModelComparisonComponents.tsx
Adding ability to download JSON export of comparison page for future reference. This includes chat settings.
Button is disabled until results are returned.
> Download JSON export of model comparison results
